### PR TITLE
Vet clinic database: query and update animals table

### PR DESCRIPTION
**Pull request by uno36**
### Project requirements
- Add a column `species` of type `string` to your `animals` table. Modify your `schema.sql` file.
- Insert the following data:
  - Animal: His name is Charmander. He was born on Feb 8th, 2020, and currently weighs -11kg. He is not neutered and he has never tried to escape.
  - Animal: Her name is Plantmon. She was born on Nov 15th, 2021, and currently weighs -5.7kg. She is neutered and she has tried to escape 2 times.
  - Animal: His name is Squirtle. He was born on Apr 2nd, 1993, and currently weighs -12.13kg. He was not neutered and he has tried to escape 3 times.
  - Animal: His name is Angemon. He was born on Jun 12th, 2005, and currently weighs -45kg. He is neutered and he has tried to escape once.
  - Animal: His name is Boarmon. He was born on Jun 7th, 2005, and currently weighs 20.4kg. He is neutered and he has tried to escape 7 times.
  - Animal: Her name is Blossom. She was born on Oct 13th, 1998, and currently weighs 17kg. She is neutered and she has tried to escape 3 times.
  - Animal: His name is Ditto. He was born on May 14th, 2022, and currently weighs 22kg. He is neutered and he has tried to escape 4 times.
- Remember to add these insertions to your `data.sql` file.

----

- Inside a transaction update the `animals` table by setting the `species` column to `unspecified`. Verify that change was made. Then roll back the change and verify that the `species` columns went back to the state before the transaction.
- Inside a transaction:
  - Update the `animals` table by setting the `species` column to `digimon` for all animals that have a name ending in `mon`.
  - Update the `animals` table by setting the `species` column to `pokemon` for all animals that don't have `species` already set.
  - Verify that changes were made.
  - Commit the transaction.
  - Verify that changes persist after commit.
- **Take a screenshot of the results of your actions.**
- Now, take a deep breath and... **Inside a transaction** delete all records in the `animals` table, then roll back the transaction.
- After the rollback verify if all records in the `animals` table still exists. After that, you can start breathing as usual ;) 
- **Take a screenshot of the results of your actions.**
- Inside a transaction:
  - Delete all animals born after Jan 1st, 2022.
  - Create a savepoint for the transaction.
  - Update all animals' weight to be their weight multiplied by -1.
  - Rollback to the savepoint
  - Update all animals' weights that are negative to be their weight multiplied by -1.
  - Commit transaction
- **Take a screenshot of the results of your actions.**
- Remember to add all these transactions to your `queries.sql` file.

----
- Write queries to answer the following questions:
  - How many animals are there?
  - How many animals have never tried to escape?
  - What is the average weight of animals?
  - Who escapes the most, neutered or not neutered animals?
  - What is the minimum and maximum weight of each type of animal?
  - What is the average number of escape attempts per animal type of those born between 1990 and 2000?
- **Take a screenshot of the results of your queries.**
- Remember to add these queries to your `queries.sql` file.
- Remember to add screenshots with the results of your queries and with the results of your play with transactions to your Pull Request description.
- screenshots: [ screenshot 1](https://drive.google.com/file/d/1Kuyy9sFcE_7K0I1jZI-NW7APPIvtL9b9/view?usp=drive_link), [ screenshot 2](https://drive.google.com/file/d/1Zz5XGcRh688lJma4ETQsoWEJmzGdLIEc/view?usp=drive_link), [ screenshot 3](https://drive.google.com/file/d/1VCN7OnZrGr6SG1PnMhbytyyYD9nSUMcK/view?usp=drive_link), [ screenshot 4](https://drive.google.com/file/d/1FmJvUumrEnCtOq_poXnb4ax8S3ftDKo0/view?usp=drive_link), [ screenshot 5](https://drive.google.com/file/d/11NnH6SO03jH5WuHep9PKNyH257bJdc5x/view?usp=drive_link), [ screenshot 6](https://drive.google.com/file/d/1wUkpS9mpJPixK_3wYdUoj3wIccgLuaT_/view?usp=drive_link), [ screenshot 7](https://drive.google.com/file/d/1ZKusdCESLPVUkxO1nW1C0xFb3lYO5S0N/view?usp=drive_link), [ screenshot 8](https://drive.google.com/file/d/1foooF5lBAdpz3TdLFIlJbl3HmEqr_6CU/view?usp=drive_link), [ screenshot 9](https://drive.google.com/file/d/17MAdperC1WJxOPCVZe4A5vDyn3MGErFV/view?usp=drive_link), [ screenshot 10](https://drive.google.com/file/d/1S5zwmXEdkHDbYMMdGB4y-bX3Tyyikd7N/view?usp=drive_link)

### CODE REVIEW

**Review by codecaiine — CHANGES_REQUESTED** [review]
Hi @uno36 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Good query setup ✔️ 

## Required Changes ♻️
- [ ] **I noticed that you missed to add a new column  `species` with a string type to animals table**  😢 . I would like to strongly recommend you to add that column and run your queries again to have the expected output and please add new screenshots as requiered for this project 👍     
```
  ALTER TABLE animals ADD species varchar(255);
```

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by uno36** [comment]
I do not understand why you can't see the species column please check again carefully, its also there on the screenshots I provided: this is my table

[table](https://drive.google.com/file/d/1xD5IrLN5bjWV_QOT5bhAG5rGODQglAPg/view?usp=sharing)

**Review by Owusu-Desmond — CHANGES_REQUESTED** [review]
Hi @uno36 , :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.



 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Your project is well documented


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Please note that everything that creates or change the tables structure should be saved in the `schema.sql` file. In your `schema.sql` file, your have no SQL command the add the `species` column to the animal table as request by the previous reviewer, Remember that if even your table have species column on your local machine, You have to add the SQL command that add the species column to the animal table. :blush: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Owusu-Desmond — APPROVED** [review]
Hi @uno36 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
